MiPlayaQR/Models/Playa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using static MiPlayaQR.Common.Helpers.Enums;

namespace MiPlayaQR.Models
{
  [Table("Playas")]
  public class Playa
  {
    public int Id { get; set; }
    public string Nombre { get; set; }
    [ForeignKey("EstadosMexico")]
    public int? IdEstado { get; set; }
    public string Descripcion { get; set; }
    public string Latitud { get; set; }
    public string Longitud { get; set; }
    public string Ubicacion { get; set; }
    public Estatus Estatus { get; set; }
    public Banderas Bandera { get; set; }
    public Estacionamiento Estacionamiento { get; set; }
    public Evento Evento { get; set; }
    public DateTime FechaCreacion { get; set; }
    public DateTime RowVersion { get; set; }
    public bool IsDeleted { get; set; }


  }
}

MiPlayaQR/ViewModels/PlayaViewModel.cs
using MiPlayaQR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static MiPlayaQR.Common.Helpers.Enums;

namespace MiPlayaQR.ViewModels
{
  public class PlayaViewModel
  {
    public int Id { get; set; }
    public string Nombre { get; set; }
    public int? IdEstado { get; set; }
    public MexicoEstado mexicoEstados { get; set; }
    public string Descripcion { get; set; }
    public string Imagen { get; set; }
    public string Latitud { get; set; }
    public string Longitud { get; set; }
    public string Ubicacion { get; set; }
    public Estatus Estatus { get; set; }
    public Banderas Bandera { get; set; }
    public Estacionamiento Estacionamiento { get; set; }
    public Evento Evento { get; set; }
    public DateTime FechaCreacion { get; set; }
    public DateTime RowVersion { get; set; }
    public bool IsDeleted { get; set; }
    public VotoPlaya VotoPlayas { get; set; }
    public VotoUsuarioPlaya VotoUsuarioPlaya { get; set; }
    public ComentarioPlaya ComentarioPlaya { get; set; }
    public List<PlayaViewModel> playas { get; set; }
    public List<MexicoEstado> ListaMexicoEstados { get; set; }
    public List<ImagenPlaya> ImagenPlayas { get; set; }
    public List<PreguntaViewModel> preguntas { get; set; }
    public List<PlayaViewModel> ListaPlayas { get; set; }
    public List<Pregunta> ListaPreguntasEncuesta { get; set; }
    public List<VotoPlayaViewModel> ListaVotoPlaya { get; set; }
    public List<ComentarioPlayaViewModel> ListaComentarioPlayas { get; set; }
    public List<int> pregRespId { get; set; }
  }
}

MiPlayaQR/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiPlayaQR.Services.IServices;
using MiPlayaQR.ViewModels;

namespace MiPlayaQR.Controllers
{
  public class MapController : Controller
  {
    private readonly IPlayaServicio _playaServicio;
    private readonly IMexicoEstadoServicio _mexicoEstadoServicio;
    private readonly UserManager<IdentityUser> _userManager;
    public MapController(IPlayaServicio playaServicio, IMexicoEstadoServicio mexicoEstadoServicio, UserManager<IdentityUser> userManager)
    {
      _playaServicio = playaServicio;
      _mexicoEstadoServicio = mexicoEstadoServicio;
      this._userManager = userManager;
    }

    public IActionResult Index()
    {
      return View();
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Menu(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Menu(string Comentario,int? idPlaya)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.ComentarioPlaya(Comentario, userId,idPlaya);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        
      }
      else
      {
        TempData["ErrorProyecto"] = response.Message;

        
      }
      return RedirectToAction("Index");
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Encuesta(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Encuesta(PlayaViewModel playa)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.Encuesta(playa, userId);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {
        TempData["ErrorProyecto"] = response.Message;

        return RedirectToAction("Index");
      }

    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> VotaPlaya(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> VotaPlaya(PlayaViewModel playa,double Puntuacion)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.CrearVotoPlaya(playa, userId,Puntuacion);


      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {
        
        TempData["ErrorProyecto"] = response.Message;
        return RedirectToAction("Index");
      }

    }

    public async Task<IActionResult> guardarComentarioPlaya(string Comentario, int? idPlaya)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.ComentarioPlaya(Comentario, userId, idPlaya);
      if (response.Success)
      {
        return Json(new { success = response.Success, msj = response.Message });
      }
      else
      {

        return Json(new { success = response.Success, msj = response.Message });
      }


    }
    public async Task<IActionResult> guardarRespuestaComentario(string RespuestaComentario, int? idComentario)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.RespuestaComentario(RespuestaComentario, userId, idComentario);
      if (response.Success)
      {
        return Json(new { success = response.Success, msj = response.Message });
      }
      else
      {

        return Json(new { success = response.Success, msj = response.Message });
      }


    }

    public async Task<IActionResult> AgregarLikesComentario(int? idComentario, bool opcion)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var comentario = await _playaServicio.AgregarLikesComentario(idComentario, userId, opcion);
      return Json(comentario);
    }
  }
}

MiPlayaQR/Controllers/PlayaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MiPlayaQR.Common.Helpers;
using MiPlayaQR.Models;
using MiPlayaQR.Services.IServices;
using MiPlayaQR.ViewModels;

namespace MiPlayaQR.Controllers
{
  public class PlayaController : Controller
  {
    private readonly IPlayaServicio _playaServicio;
    private readonly IMexicoEstadoServicio _mexicoEstadoServicio;

    public PlayaController( IPlayaServicio playaServicio, IMexicoEstadoServicio mexicoEstadoServicio)
    {
      _playaServicio = playaServicio;
      _mexicoEstadoServicio = mexicoEstadoServicio;
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Index()
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa.playas = await _playaServicio.ObtenerListPlayas();
      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Crear()
    {
      PlayaViewModel playa = new PlayaViewModel();
      playa.ListaMexicoEstados = await _mexicoEstadoServicio.ObtenerListaEstados();
      var listaEstados = await _mexicoEstadoServicio.ObtenerListaEstados();
      ViewBag.ListaMexicoEstados = new SelectList((from a in listaEstados
                                                   select new
                                                   {
                                                     IdEstado = a.Id,
                                                     Nombre = a.Nombre
                                                   }), "IdEstado", "Nombre");
      
      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Crear(Playa playa, List<IFormFile> imagen)
    {

      var response = await _playaServicio.Crear(playa, imagen);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {


        TempData["ErrorProyecto"] = response.Message;

        return RedirectToAction("Index");
      }

    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Editar(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);
      if (playa == null)
      {
        return RedirectToAction("Index");
      }
      playa.ListaMexicoEstados = await _mexicoEstadoServicio.ObtenerListaEstados();
      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Editar(Playa playa, List<IFormFile> imagen)
    {

      var response = await _playaServicio.Editar(playa, imagen);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {


        TempData["ErrorProyecto"] = response.Message;

        return RedirectToAction("Index");
      }

    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Detalle(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);
      if(playa == null)
      {
        return RedirectToAction("Index");
      }
      playa.ListaMexicoEstados = await _mexicoEstadoServicio.ObtenerListaEstados();
      return View(playa);
    }

    [HttpGet]
    public async Task<IActionResult> Playas(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();
      playa.playas = await _playaServicio.ObtenerListaPlayas();
      return View(playa);
    }


    //funciones
    public async Task<IActionResult> ObtenerPlayas()
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa.playas = await _playaServicio.ObtenerListPlayas();


      return Json(playa);
    }
    public async Task<IActionResult> ObtenerListaPlayasComp()
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa.playas = await _playaServicio.ObtenerListaPlayas();


      return Json(playa);
    }
    public async Task<IActionResult> ObtenerListaPlayas()
    {


      var listaPlayas = await _playaServicio.ObtenerListPlayas();


      return Json(listaPlayas);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    public async Task<IActionResult> ObtenerListPreguntas()
    {


      var listaPreguntas = await _playaServicio.ObtenerListPreguntas();


      return Json(listaPreguntas);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    public async Task<IActionResult> ObtenerRespuestasPlaya()
    {

      var listaPlayas = await _playaServicio.ObtenerRespuestasPlaya();

      return Json(listaPlayas);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    public async Task<IActionResult> ObtenerPlayaEditar(int? idPlaya)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(idPlaya);


      return Json(playa);
    }

    public async Task<IActionResult> ObtenerComentariosPlaya(int? idPlaya)
    {

     var comentariosPlaya = await _playaServicio.obtenerComentarioPlaya(idPlaya);
      return Json(comentariosPlaya);
    }
    public async Task<IActionResult> ObtenerRespuestaComentarios(int? idComentario)
    {

      var respuestasComentario = await _playaServicio.obtenerRespuestasComentario(idComentario);
      return Json(respuestasComentario);
    }
    
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    public async Task<IActionResult> EliminarPlayaId(int? id)
    {
      var response = await _playaServicio.Eliminar(id);
      if (response.Success)
      {
        return Json(new { success = response.Success, msj = response.Message });
      }
      else
      {

        return Json(new { success = response.Success, msj = response.Message });
      }


    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> RespuestaEncuesta()
    {

      PlayaViewModel playa = new PlayaViewModel();

      playa.ListaPlayas = await _playaServicio.ObtenerRespuestasPlaya();

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> RespuestaVotacion()
    {

      PlayaViewModel playa = new PlayaViewModel();

      playa.ListaPlayas = await _playaServicio.ObtenerVotacionesPlayas();

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> EncuestaPreguntasRespuestas()
    {

      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPreguntasRespuestasPlaya();

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Root,Colaborador")]
    [HttpPost]
    public async Task<IActionResult> EncuestaPreguntasRespuestas(string pregunta, List<string> respuesta)
    {
      var response = await _playaServicio.AgregarPreguntasRespuestaPlayas(pregunta, respuesta);
      if (response.Success)
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {
        TempData["SuccessProyecto"] = response.Message;
        
        return RedirectToAction("Index");
      }

    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    public async Task<IActionResult> ObtenerPreguntasRespuestasPlaya()
    {


      var listaPreguntas = await _playaServicio.ObtenerPreguntasRespuestasPlaya();


      return Json(listaPreguntas);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    public async Task<IActionResult> ObtenerVotacionesPlayas()
    {


      var listaPreguntas = await _playaServicio.ObtenerVotacionesPlayas();


      return Json(listaPreguntas);
    }
  }
}

MiPlayaQR/Views/Playa/Crear.cshtml
@model MiPlayaQR.ViewModels.PlayaViewModel;
@{
    ViewData["Title"] = "Crear";
}


@using static MiPlayaQR.Common.Helpers.Enums;
<style>
    .regresarBtn {
        margin-top: 20px;
        float: right;
        font-size: 20px;
    }

    /* Set the size of the div element that contains the map */
    #map {
        height: 400px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }
</style>




<div class="controlRoutes">
    <div class="row">
        <div class="col">
            <h1>@ViewData["Title"] playas</h1>

        </div>
        <div class="col">
            <a class="btn btn-secondary  regresarBtn" asp-controller="Playa" asp-action="Index" title="Regresar">

                <i class="fas fa-arrow-left"></i>
                <span class="k-hidden-mobile">Regresar</span>
            </a>
        </div>
    </div>

</div>
<form asp-action="Crear" enctype="multipart/form-data" class="k-form" id="k_form" method="post" autocomplete="off">
    @Html.AntiForgeryToken()

    <label>Ingresa el Nombre de la playa</label>
    <input type="text" class="form-control" asp-for="Nombre" id="NombrePlaya" />
    <label>Ingresa la latitud de la playa</label>
    <input type="number" class="form-control" asp-for="Latitud" id="LatitudPlaya" />
    <label>Ingresa la longitud de la playa</label>
    <input type="number" class="form-control" asp-for="Longitud" id="LongitudPlaya" />

    <div class="row">
        <input type="button" onclick="ubicacion()" value="Ubicación" />
        <input type="button" onclick="traffic()" value="Trafico" />
        <div id="map"></div>

    </div>

    <script>

        var marker;
        var infoWindow;
        function initMap() {
            /*
            $.post("/Playa/ObtenerPlayaEditar/", { idPlaya: 1 })
              .done(function (data) {
                console.log(data);
              });
              */
            var cancun = { lat: 21.122631, lng: -86.778341 };
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 13,
                center: cancun
            });

            infoWindow = new google.maps.InfoWindow;
            map.setCenter(cancun);

            google.maps.event.addListener(map, 'click', function (event) {
                placeMarker(event.latLng);
            });

        }


        function placeMarker(location) {
            if (marker) {
                marker.setPosition(location);
                info(location);
            } else {
                marker = new google.maps.Marker({
                    position: location,
                    map: map,
                    draggable: false,
                    animation: google.maps.Animation.DROP
                });
                info(location);
            }




        }

        function info(location) {
            var lat = location.lat();
            var lng = location.lng();

            var latstr = lat.toString();
            var lngstr = lng.toString();

            var latres = latstr.slice(0, 10);
            var lngres = lngstr.slice(0, 10);


            $("#LatitudPlaya").val(latres);
            $("#LongitudPlaya").val(lngres);


        }

        function centrar() {
            var cancun = { lat: 21.122631, lng: -86.778341 };
            map.setCenter(cancun);
        }


        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                'Error: The Geolocation service failed.' :
                'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }


        function ubicacion() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    // console.log("entro");


                    map.setCenter(pos);
                    var marker2 = new google.maps.Marker({
                        position: {
                            lat: position.coords.latitude,
                            lng: position.coords.longitude
                        },
                        animation: google.maps.Animation.DROP,
                        content: '<h4>Tu ubicación</h4>'
                    });
                    var contentString =
                        '<div class="content"> Tu ubicación</div>';
                    var infoWindow = new google.maps.InfoWindow({

                        content: contentString
                    });
                    marker2.setMap(map);
                    infoWindow.open(map, marker2);
                }, function () {
                    handleLocationError(true, infoWindow, map.getCenter());
                });




            } else {
                // Browser doesn't support Geolocation
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }
    </script>













    <label>Imagen del componente</label>
    <div class="custom-file">
        <input type="file" accept="image/*" id="inputFile" class="custom-file-input" name="imagen" />
        <label class="custom-file-label" for="inputFile">Selecciona una imagen</label>
    </div>

    <div class="col-lg-12 inputx" id="contenedor" style="display:none;">
        <img id="imgSalida" src="~/assets/Imagenes/no-image.png" alt="Foto" class="img-fluid img-responsive">
    </div>
    <div class="col-xl-12 inputx" id="contenedorDefecto">
        <div class="k-iconbox">
            <div class="k-iconbox__icon">
                <div class="k-iconbox__icon-bg k-header__topbar-icon"></div>
                <i class="flaticon2-image-file"></i>
            </div>
            <div class="k-scroll" data-scroll="true" style="height: 110px;" id="containerScroll">
                <h3 style="text-align: center;">Ninguna imagen cargada</h3>
            </div>
        </div>
    </div>



    <label>Selecciona el estado de la Republica de la playa</label>
    <select asp-for="IdEstado" class="form-control" asp-items="ViewBag.ListaMexicoEstados" id="IdEstado">
        <option value="" disabled hidden selected>Selecciona un estado</option>

    </select>

    <label>Selecciona la bandera de la playa</label>
    <select class="form-control" asp-for="Bandera" id="idBandera">
        <option value="0">Verde</option>
        <option value="1">Amarilla</option>
        <option value="2">Roja</option>
        <option value="3">Blanca</option>
        <option value="4">Negra</option>
    </select>
    <label>Selecciona la ocupacion del estacionamiento de la playa</label>
    <select class="form-control" asp-for="Estacionamiento" id="idEstacionamiento">
        <option value="0">LLeno</option>
        <option value="1">Vacio</option>
        <option value="2">Disponible</option>
    </select>
    <label>Selecciona el evento actual</label>
    <select class="form-control" asp-for="Evento" id="idEvento">
        <option value="0">Desovacion</option>
        <option value="1">Ninguno</option>
    </select>
    <button type="submit" class="btn btn-success">Enviar</button>
</form>
<script>
    $(document).ready(function () {

        $(function () {
            $('#inputFile').change(function (imagen) {
                agregarImagen(imagen);
            });

            function agregarImagen(imagen) {
                var file = imagen.target.files[0],
                    imageType = /image.*/;

                if (!file.type.match(imageType))
                    return;

                var reader = new FileReader();
                reader.onload = fileOnload;
                reader.readAsDataURL(file);
            }

            function fileOnload(imagen) {
                var result = imagen.target.result;
                $('#contenedorDefecto').hide();
                $('#contenedor').show();
                $('#imgSalida').attr("src", result);
            }
        })

    });
</script>
<script defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC9Tujz5CC6WGhh0ZGWFL9Tp5FD3IkJc4Y&callback=initMap">
</script>

MiPlayaQR/Views/Playa/Editar.cshtml
@model MiPlayaQR.ViewModels.PlayaViewModel;
@{
  ViewData["Title"] = "Editar";
}
<style>
  .regresarBtn {
    margin-top: 20px;
    float: right;
    font-size: 20px;
  }
</style>
<div class="controlRoutes">
  <div class="row">
    <div class="col">
      <h1>@ViewData["Title"] playas</h1>

    </div>
    <div class="col">
      <a class="btn btn-secondary  regresarBtn" asp-controller="Playa" asp-action="Index" title="Regresar">

        <i class="fas fa-arrow-left"></i>
        <span class="k-hidden-mobile">Regresar</span>
      </a>
    </div>
  </div>

</div>

<form asp-action="Editar" enctype="multipart/form-data" class="k-form" id="k_form" method="post" autocomplete="off">
  @Html.AntiForgeryToken()

  <label>Ingresa el Nombre de la playa</label>
  <input type="text" class="form-control" asp-for="Nombre" id="NombrePlaya" value="@Model.Nombre" />
  <label>Ingresa la latitud de la playa</label>
  <input type="number" class="form-control" asp-for="Latitud" id="LatitudPlaya" value="@Model.Latitud" />
  <label>Ingresa la longitud de la playa</label>
  <input type="number" class="form-control" asp-for="Longitud" id="LongitudPlaya" value="@Model.Longitud" />
  <label>Imagen</label>
  <div class="custom-file">
    <input type="file" accept="image/*" id="inputFile" class="custom-file-input" name="imagen" />
    <label class="custom-file-label" for="inputFile">Selecciona una imagen</label>
  </div>
  <img id="imgSalida" src="~/assets/Playas/@Model.Id/Imagenes/@Model.ImagenPlayas.FirstOrDefault().URL" alt="Foto" class="img-fluid img-responsive">
  <label>Selecciona el estado de la Republica de la playa</label>
  <select class="form-control" asp-for="IdEstado" id="IdEstado">
    @foreach (var Estado in Model.ListaMexicoEstados)

    {
      if (Estado.Nombre == Model.mexicoEstados.Nombre)
      {
        <option value="@Estado.Id" selected>@Estado.Nombre</option>
      }
      else
      {
        <option value="@Estado.Id">@Estado.Nombre</option>
      }

    }
  </select>
  <label>Selecciona la bandera de la playa</label>
  <select class="form-control" asp-for="Bandera" id="idBandera">
    <option value="0">Verde</option>
    <option value="1">Amarilla</option>
    <option value="2">Roja</option>
    <option value="3">Blanca</option>
    <option value="4">Negra</option>
  </select>
  <label>Selecciona la ocupacion del estacionamiento de la playa</label>
  <select class="form-control" asp-for="Estacionamiento" id="idEstacionamiento">
    <option value="0">LLeno</option>
    <option value="1">Vacio</option>
    <option value="2">Disponible</option>
  </select>
  <label>Selecciona el evento actual</label>
  <select class="form-control" asp-for="Evento" id="idEvento">
    <option value="0">Desovacion</option>
    <option value="1">Ninguno</option>
  </select>
  <button type="submit" class="btn btn-success">Enviar</button>
</form>