MiPlayaQR/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiPlayaQR.Services.IServices;
using MiPlayaQR.ViewModels;

namespace MiPlayaQR.Controllers
{
  public class MapController : Controller
  {
    private readonly IPlayaServicio _playaServicio;
    private readonly IMexicoEstadoServicio _mexicoEstadoServicio;
    private readonly UserManager<IdentityUser> _userManager;
    public MapController(IPlayaServicio playaServicio, IMexicoEstadoServicio mexicoEstadoServicio, UserManager<IdentityUser> userManager)
    {
      _playaServicio = playaServicio;
      _mexicoEstadoServicio = mexicoEstadoServicio;
      this._userManager = userManager;
    }

    public IActionResult Index()
    {
      return View();
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Menu(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Menu(string Comentario,int? idPlaya)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.ComentarioPlaya(Comentario, userId,idPlaya);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        
      }
      else
      {
        TempData["ErrorProyecto"] = response.Message;

        
      }
      return RedirectToAction("Index");
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> Encuesta(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Encuesta(PlayaViewModel playa)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.Encuesta(playa, userId);

      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {
        TempData["ErrorProyecto"] = response.Message;

        return RedirectToAction("Index");
      }

    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpGet]
    public async Task<IActionResult> VotaPlaya(int? id)
    {
      PlayaViewModel playa = new PlayaViewModel();

      playa = await _playaServicio.ObtenerPlaya(id);

      return View(playa);
    }
    [Authorize(Roles = "Administrador,Usuario,Root,Colaborador")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> VotaPlaya(PlayaViewModel playa,double Puntuacion)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.CrearVotoPlaya(playa, userId,Puntuacion);


      if (response.Success) //Validamos si el cargo se creó.
      {
        TempData["SuccessProyecto"] = response.Message;
        return RedirectToAction("Index");
      }
      else
      {
        
        TempData["ErrorProyecto"] = response.Message;
        return RedirectToAction("Index");
      }

    }

    public async Task<IActionResult> guardarComentarioPlaya(string Comentario, int? idPlaya)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.ComentarioPlaya(Comentario, userId, idPlaya);
      if (response.Success)
      {
        return Json(new { success = response.Success, msj = response.Message });
      }
      else
      {

        return Json(new { success = response.Success, msj = response.Message });
      }


    }
    public async Task<IActionResult> guardarRespuestaComentario(string RespuestaComentario, int? idComentario)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var response = await _playaServicio.RespuestaComentario(RespuestaComentario, userId, idComentario);
      if (response.Success)
      {
        return Json(new { success = response.Success, msj = response.Message });
      }
      else
      {

        return Json(new { success = response.Success, msj = response.Message });
      }


    }

    public async Task<IActionResult> AgregarLikesComentario(int? idComentario, bool opcion)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      var comentario = await _playaServicio.AgregarLikesComentario(idComentario, userId, opcion);
      return Json(comentario);
    }
  }
}

MiPlayaQR/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - MiPlayaQR</title>
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <link href="~/datatables/datatables/datatables.bundle.css" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="~/css/Datatable/datatables.min.css" />
  <script type="text/javascript" src="~/js/Datatable/pdfmake.min.js"></script>
  <script type="text/javascript" src="~/js/Datatable/vfs_fonts.js"></script>
  <script type="text/javascript" src="~/js/Datatable/datatables.min.js"></script>
  <script type="text/javascript" src="~/js/Datatable/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="~/js/Datatable/dataTables.responsive.min.js"></script>
  <link rel="stylesheet" href="~/css/Bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="~/css/Menu/Menu.css">
  <environment include="Development">

    <link rel="stylesheet" href="~/fontawesome-free-5.14.0-web/css/all.min.css">
    <link rel="stylesheet" href="~/css/_Layout/Index.css">

  </environment>
  <environment exclude="Development">


  </environment>
  <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
  <header>
  </header>
  <div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
      <div class="sidebar-header" id="divLogo">
        <img id="logo" style="width: 100%;" src="~/assets/Imagenes/Logo.png" />
      </div>


      <ul class="list-unstyled components">

        @if (User.IsInRole("Administrador") || User.IsInRole("Root"))
        {
          <li>

            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
              <i class="fas fa-copy"></i> Panel
            </a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li>
                <a asp-area="" asp-controller="Playa" asp-action="Index"><i class="fas fa-umbrella-beach"></i>Gestión Playas</a>
              </li>
              <li>
                <a asp-area="" asp-controller="Administrador" asp-action="Usuarios"><i class="fas fa-users-cog"></i>Usuarios</a>
              </li>
              <li>
                <a asp-area="" asp-controller="Administrador" asp-action="Roles"><i class="fas fa-ruler"></i>Roles</a>
              </li>
              <li>
                <a asp-area="" asp-controller="Contacto" asp-action="Contactos"><i class="fas fa-ruler"></i>Contactos</a>
              </li>
            </ul>
          </li>
        }
        <li>
          <a asp-controller="Map" asp-action="Index"><i class="fas fa-map-marked"></i>Mapa</a>
        </li>
        <li>
          <a asp-area="" asp-controller="Playa" asp-action="Playas"><i class="fas fa-umbrella-beach"></i>Playas</a>
        </li>
        <li>
          <a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i>Home</a>
        </li>

        <li>
          <a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fas fa-question"></i>Privacy</a>
        </li>
        <li>
          <a asp-area="" asp-controller="Contacto" asp-action="Index"><i class="fas fa-envelope"></i>Contacto</a>
        </li>
        <li>
          <a asp-area="" asp-controller="Nosotros" asp-action="Index"><i class="fas fa-laptop-code"></i>Nosotros</a>
        </li>
      </ul>

    </nav>

    <!-- Page Content  -->
    <div id="content">

      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">

          <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>

          </button>


          @if (SignInManager.IsSignedIn(User))
          {
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-user-alt"></i> Perfil
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">

                <li class="nav-item active opcionesLogin" >
                  <a asp-controller="Account" asp-action="Perfil" class="nav-link"><i class="fas fa-user-tag"></i>@User.Identity.Name.ToUpperInvariant()!</a>
                </li>
                <li class="nav-item active opcionesLogin">
                  <form method="post" asp-controller="Account" asp-action="Logout">
                    <button id="logout" type="submit" class="nav-link btn btn-link"><i class="fas fa-sign-out-alt"></i>Cerrar</button>
                  </form>
                </li>
              </ul>
            </div>
          }
          else
          {
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-user-edit"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">

                <li class="nav-item active opcionesLogin">
                  <a asp-controller="Account" asp-action="Register" class="nav-link ">
                    <i class="fas fa-user-edit"></i>Registrarse
                  </a>
                </li>
                <li class="nav-item active opcionesLogin">
                  <a asp-controller="Account" asp-action="Login" class="nav-link">
                    <i class="fas fa-sign-in-alt"></i> Iniciar sesión
                  </a>
                </li>
              </ul>
            </div>
          }
        </div>
      </nav>

      @if (TempData["SuccessProyecto"] != null)
      {
        <div class="alert alert-success fade show" role="alert">
          <div class="alert-text"><strong>¡Éxito!</strong> @TempData["SuccessProyecto"]<i class="fa fa-check-circle"></i></div>
          <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="fas fa-times-circle"></i></span>
            </button>
          </div>
        </div>
      }
      @if (TempData["ErrorProyecto"] != null)
      {
        <div class="alert alert-danger fade show" role="alert">
          <div class="alert-text"><strong>¡Advertencia!</strong> @TempData["ErrorProyecto"]<i class="fas fa-exclamation-circle"></i></div>
          <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="fas fa-times-circle"></i></span>
            </button>
          </div>
        </div>
      }
    <div id="ContenidoMiPlayaQR">
      @RenderBody()
    </div>
    </div>
  </div>
  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2020 - MiPlayaQR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>

  <environment include="Development">

    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/js/sweetalert/sweetalert2@9.js"></script>
  </environment>
  <environment exclude="Development">
    <script src="~/js/jquery/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="~/js/Bootstrap/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
  </environment>
  <script src="~/js/site.js" asp-append-version="true"></script>

  @RenderSection("Scripts", required: false)
  <!-- Popper.JS -->
  <script src="~/js/Bootstrap/popper.min.js"></script>
  <!-- Bootstrap JS -->
  <script src="~/js/Bootstrap/bootstrap.min.js"></script>

  <script type="text/javascript">
    var contador = 1;
    $(document).ready(function () {
      /*
      if (screen.width < 767) {
        document.getElementById("logo").width = "50";

      } else {
        document.getElementById("logo").width = "200";

      }
      */
      $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
        /*
        if (screen.width > 767) {
          document.getElementById("logo").width = "50";
          if (contador == 0) {
            document.getElementById("logo").width = "10%";
            contador++;
          } else if (contador == 1) {
            document.getElementById("logo").width = "50";

            contador--;
          }
        }
        */

      });
    });
  </script>

</body>
</html>